# Generated by Django 5.1.15 on 2026-06-20 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('description', models.TextField(blank=True, verbose_name='توضیح')),
                ('icon', models.CharField(blank=True, help_text='کلید آیکن سمت فرانت', max_length=60, verbose_name='آیکن')),
                ('route', models.CharField(blank=True, help_text='route سمت فرانت', max_length=200, verbose_name='مسیر')),
                ('group', models.CharField(blank=True, max_length=80, verbose_name='گروه منو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('required_permission', models.ForeignKey(blank=True, help_text='خالی = برای همهٔ کاربران واردشده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards', to='identity.permission')),
            ],
            options={
                'verbose_name': 'داشبورد',
                'verbose_name_plural': 'داشبوردها',
                'ordering': ['order', 'title'],
            },
        ),
    ]
