# Generated by Django 5.1.15 on 2026-06-22 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_dashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('widget_type', models.CharField(choices=[('kpi', 'شاخص (KPI)'), ('chart_line', 'نمودار خطی'), ('chart_bar', 'نمودار میله\u200cای'), ('chart_pie', 'نمودار دایره\u200cای'), ('list', 'فهرست'), ('table', 'جدول'), ('map', 'نقشه'), ('quick_action', 'اقدام سریع')], max_length=20, verbose_name='نوع')),
                ('section', models.CharField(choices=[('kpis', 'شاخص\u200cها'), ('quick_actions', 'اقدامات سریع'), ('charts', 'نمودارها'), ('lists', 'فهرست\u200cها'), ('personal', 'پروندهٔ من'), ('admin', 'مدیریت سامانه')], db_index=True, max_length=20, verbose_name='بخش')),
                ('data_key', models.CharField(blank=True, help_text='منبع آماری که بعداً مقدار این ویجت را تأمین می\u200cکند', max_length=120, verbose_name='کلید داده')),
                ('route', models.CharField(blank=True, max_length=200, verbose_name='مسیر فرانت')),
                ('icon', models.CharField(blank=True, max_length=60, verbose_name='آیکن')),
                ('size', models.CharField(choices=[('sm', 'کوچک'), ('md', 'متوسط'), ('lg', 'بزرگ')], default='md', max_length=4, verbose_name='اندازه')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='تنظیمات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('required_permission', models.ForeignKey(blank=True, help_text='خالی = برای همهٔ کاربران واردشده', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='identity.permission')),
            ],
            options={
                'verbose_name': 'ویجت داشبورد',
                'verbose_name_plural': 'ویجت\u200cهای داشبورد',
                'ordering': ['section', 'order', 'title'],
            },
        ),
    ]
