# Generated by Django 5.1.15 on 2026-06-24 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='کد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='کد')),
                ('type', models.CharField(choices=[('hq', 'ستاد مرکزی'), ('province_org', 'تشکیلات استان'), ('suborg', 'سازمان زیرمجموعه'), ('department', 'اداره'), ('unit', 'واحد'), ('center', 'مرکز')], db_index=True, max_length=20, verbose_name='نوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_units', to='hr.city')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='hr.orgunit')),
            ],
            options={
                'verbose_name': 'واحد سازمانی',
                'verbose_name_plural': 'واحدهای سازمانی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی')),
                ('personnel_no', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='شماره پرسنلی')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('employment_type', models.CharField(blank=True, choices=[('official', 'رسمی'), ('contractual', 'قراردادی'), ('contractor', 'پیمانکاری'), ('volunteer', 'داوطلب'), ('other', 'سایر')], db_index=True, max_length=20, verbose_name='نوع استخدام')),
                ('employment_status', models.CharField(choices=[('active', 'شاغل'), ('retired', 'بازنشسته'), ('terminated', 'قطع همکاری'), ('suspended', 'تعلیق')], db_index=True, default='active', max_length=20, verbose_name='وضعیت اشتغال')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاریخ جذب')),
                ('is_retired', models.BooleanField(default=False, verbose_name='بازنشسته')),
                ('job_title', models.CharField(blank=True, max_length=150, verbose_name='عنوان شغلی')),
                ('children_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد فرزند')),
                ('service_years', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سابقه (سال)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین به\u200cروزرسانی از HR')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('org_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='hr.orgunit')),
            ],
            options={
                'verbose_name': 'پرسنل',
                'verbose_name_plural': 'پرسنل',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation', models.CharField(choices=[('spouse', 'همسر'), ('child', 'فرزند'), ('father', 'پدر'), ('mother', 'مادر'), ('other', 'سایر')], max_length=10, verbose_name='نسبت')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_id', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, choices=[('m', 'مرد'), ('f', 'زن')], max_length=1, verbose_name='جنسیت')),
                ('is_student', models.BooleanField(default=False, verbose_name='محصل/دانشجو')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='hr.personnel')),
            ],
            options={
                'verbose_name': 'فرد تحت تکفل',
                'verbose_name_plural': 'افراد تحت تکفل',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelDecree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decree_no', models.CharField(blank=True, max_length=50, verbose_name='شماره حکم')),
                ('decree_date', models.DateField(blank=True, null=True, verbose_name='تاریخ حکم')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='مقادیر حکم')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='از تاریخ')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تا تاریخ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decrees', to='hr.personnel')),
            ],
            options={
                'verbose_name': 'حکم پرسنلی',
                'verbose_name_plural': 'احکام پرسنلی',
                'ordering': ['-decree_date'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='کد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='personnel',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='hr.province'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_units', to='hr.province'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='hr.province'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('province', 'name'), name='uniq_city_in_province'),
        ),
    ]
